version: '3.8'
services:
  pg_data:
    container_name: pg_data
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: my_data
      POSTGRES_USER: my_data
      POSTGRES_PASSWORD: my_data
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  
volumes:
  pg_data:
    driver: local
